apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-pd-sc
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
parameters: 
  type: pd-standard
  fsType: ext4