apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-ns-quota 
  namespace: dev-team
spec:
  hard: 
    requests.cpu: "1"  
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "10"

#1 CPU = 1000m = 10x100m (6 Pods)
#1 Gi  = 1000Mi = 6x150Mi (6 Pods)