services:
  todo-app:
    build:
      context: ./app
    environment:
      - NODE_ENV= production
    ports:
      - 3000:3000
    links:
      - todo-database

  todo-database:
    image: mongo:6 
    ports:
      - 27017:27017
