#To add label and taint
# kubectl label node <node name> gpuEnabled=yes (per below node selector attribute)
# kubectl taint node <node name> gpuEnabled=yes:Noschedule (per below tolerations)
#To remove label and taint
# kubectl label node <node name> gpuEnabled- (per below node selector attribute)
# kubectl taint node <node name> gpuEnabled:Noschedule-  (per below tolerations)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tol-example
  labels: 
    app: nginx-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "gpuEnabled"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      nodeSelector:
        gpuEnabled: "yes"