---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev-team
spec:
  containers:
    - name: nginx 
      image: nginx:1.27 
      ports:
        - containerPort: 80
      resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "140m"
            memory: "140Mi"