apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-file-vol 
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.26.40.2
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: manual-file-claim 