apiVersion: apps/v1 
kind: Deployment #Controller
metadata:
  name: alpine-deploy
  labels:
    app: alpine 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alpine  
  template:
    metadata:
      name: alpine
      labels:
        app: alpine 
    spec:
      containers:
        - name: alpine  
          image: nextopsacrt26.azurecr.io/mysql:latest
          ports:
            - containerPort: 80          