---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  containers:
    - name: nginx 
      image: nginx:1.27 
      ports:
        - containerPort: 80
    - name: helper
      image: busybox